spring:
  application:
    name: rocketmq-producer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.52.185.51:3308/db_user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456@vt
server:
  port: 8081
rocketmq:
  name-server: 8.134.98.156:9876
  producer:
    group: my-boot-producer-group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2



##mybatis-plus配置
#mybatis-plus:
#  configuration:
#    #sql日志打印
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    #开启驼峰命名匹配
#    map-underscore-to-camel-case: true
#    #mapper文件
#  mapper-locations: classpath:mapper/${project.database}/**/*.xml,classpath:mapper/*.xml
#  #数据库实体类的包全路径，方便在mapper.xml中不许使用实体类的全路径，写类名就行（不区分大小写）
#  type-aliases-package: com.zhuang.mp.entity
#  global-config:
#    db-config:
#      #逻辑删除
#      logic-delete-value: 1       # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0   # 逻辑未删除值(默认为 0
#      logic-delete-field: deleted #全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置实体类字段上加上@TableLogic注解)
